name: Dependabot Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Build dist files
        run: npm run build
      - name: Commit changes
        run: |
          git config --global user.name 'Dependabot'
          git config --global user.email 'dependabot@noreply.github.com'
          git commit -am "ci: build dist with updated dependencies [skip-ci]"
          git push
